# Generated by Django 4.1.5 on 2023-02-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_post', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
