# Generated by Django 4.1.5 on 2023-02-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_like', '0001_initial'),
        ('social_post', '0001_initial'),
        ('social_response', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_post.post'),
        ),
        migrations.AddField(
            model_name='like',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_response.response'),
        ),
    ]
